#!/bin/bash

# Wait a bit to get focus
sleep 0.5

python_pty_spawn="if command -v python3 &>/dev/null; then python3 -c 'import pty; pty.spawn(\"/bin/bash\")'; else python -c 'import pty; pty.spawn(\"/bin/bash\")'; fi"

# Run a command on the remote shell to determine if python3 is available
xdotool type --delay 50 "${python_pty_spawn}"
xdotool key Return

sleep 0.5
xdotool key ctrl+z
sleep 0.5

xdotool type --delay 50 "stty raw -echo"
xdotool key Return

xdotool type --delay 50 "fg"
xdotool key Return

xdotool type --delay 50 "export SHELL=bash"
xdotool key Return

xdotool type --delay 50 "export TERM=xterm-256color"
xdotool key Return


# Hard coded because rofi isn't loading a terminal environment
rows=52
cols=238

xdotool type --delay 50 "stty rows $rows columns $cols"
xdotool key Return

xdotool type --delay 50 "reset"
xdotool key Return

# Run a pty spwan againt to make it fully interactive
xdotool type --delay 50 "${python_pty_spawn}"
xdotool key Return
