#!/bin/bash

# Haal terminalgrootte op
rows=$(stty size | awk '{print $1}')
cols=$(stty size | awk '{print $2}')

# Commando's om de reverse shell te fixen
commands=(
    "python -c 'import pty; pty.spawn(\"/bin/bash\")'"
    "xdotool key ctrl+z"
    "stty raw -echo"
    "fg"
    "reset"
    "export SHELL=bash"
    "export TERM=xterm-256color"
    "stty rows $rows columns $cols"
)

# Gebruik xdotool om alles uit te voeren
for cmd in "${commands[@]}"; do
    xdotool type --delay 100 "$cmd"
    xdotool key Return
    sleep 0.2
done
