#!/bin/bash
xdotool type --delay 10 "gobuster dir -u http://10.129.72.33/ -w /usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt -t 40 -b 400,404,403,429 -e -X /usr/share/wordlists/seclists/Discovery/Web-Content/web-extensions.txt"
